export enum ACTION_CONSTANTS {
	TYPE = "type",
	CLASS_DETAIL_FETCHED = "CLASS_DETAIL_FETCHED",

	SHOW_LOADER = "SHOW_LOADER",
	HIDE_LOADER = "HIDE_LOADER",
	ERROR_HANDLER = "ERROR_HANDLER",
	EXCEPTION_HANDLER = "EXCEPTION_HANDLER"
}