export enum ACTION_CONSTANTS {
	TYPE = "type",
	FETCH_USER_DETAIL = "FETCH_USER_DETAIL",
	SHOW_LOADER="SHOW_LOADER",
	HIDE_LOADER="HIDE_LOADER",
	ERROR_HANDLER="ERROR_HANDLER",
	EXCEPTION_HANDLER="EXCEPTION_HANDLER"
}